language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3

before_install: gem install bundler

matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 1.9
      gemfile: gemfiles/ruby-1.9.gemfile
